### ISSUE TITLE
Getting warning for action using Node 12 in github actions

### ISSUE THREAD

**Issue by akshat-trivedi-maersk** [bduff9/use-npmrc#292]
Getting this warning, even after updating my workflow from using bduff9/use-npmrc@v1.1 to bduff9/use-npmrc@v1.2

"Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: bduff9/use-npmrc@v1.2."

**Comment by bduff9** [comment]
This has been fixed in v2.0.0
